# Exploración de datos

In [2]:
import pandas as pd

In [27]:
df_customer = pd.read_csv("../Data/eci_customer_data.csv")
df_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801923 entries, 0 to 801922
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   client_id        801923 non-null  int64
 1   phone_number     705749 non-null  object
 2   email_address    657079 non-null  object
 3   city             801923 non-null  object
 4   state            801923 non-null  object
 5   zip_code         734663 non-null  object
 6   education_level  682042 non-null  object
 7   occupation       657407 non-null  object
 8   loyalty_member   762074 non-null  object
 9   loyalty_number   440681 non-null  object
 10  loyalty_points   392749 non-null  object
dtypes: int64(1), object(10)
memory usage: 67.3+ MB

In [12]:
df_customer.sample(25)

,client_id,phone_number,email_address,city,state,zip_code,education_level,occupation,loyalty_member,loyalty_number,loyalty_points
335842,927723,(770) 508-6389,lisamorales@gmail.com,Augusta,GA,30901,NaN,Manager,No,NaN,NaN
6273,508075,(919) 493-0512,andrewrogers@yahoo.com,Greensboro,NC,27410,PhD,Specialist,1,LP369405,3562
83037,605716,(503) 246-8266,samplecool623@gmail.com,Salem,OR,97302,Bachelor's Degree,Accountant,Yes,LOYAL-325242,690
486322,1120083,(213) 407-1339,member24062+store@hotmail.com,Sacramento,CA,NaN,NaN,Professor,Yes,LP106376,6860
47402,560122,(918) 811-1525,NaN,Lawton,OK,73507,NaN,Specialist,No,NaN,NaN
130530,666304,(508) 461-3629,NaN,Worcester,MA,01609,Bachelors,NaN,True,448973,885
66166,583989,(508) 452-0208,MEMBER2000@AOL.COM,Worcester,MA,01609,Some College,Sales Representative,Yes,MEMBER5602,6432
278236,854786,(614) 305-7344,sample50798+shopping@gmail.com,Columbus,OH,43229,HS,Manager,Yes,NaN,NaN
482846,1115730,(412) 488-3062,memberbest794@gmail.com,Reading,PA,19606,Bachelors,Manager,N,NaN,677
274094,849461,(770) 392-6214,NaN,Augusta,GA,30901,Bachelors,Teacher,Y,1390-8694,NaN
424864,1041286,NaN,NaN,Detroit,MI,48201,HS,NaN,Yes,LOYAL-724689,117
351097,947194,(718) 708-0502,elizabeth.ortiz@hotmail.com,New York,NY,10025,Bachelor's Degree,Retail Worker,Yes,LP154369,89
48795,561858,NaN,NaN,Columbia,SC,29201,Bachelor's Degree,Driver,No,NaN,NaN
644517,1321248,(215) 581-6135,customer11950@gmail.com,Allentown,PA,18101,NaN,Teacher,Yes,396680,NaN
442757,1064370,(713) 973-7970,ericstewart@verizon.net,El Paso,TX,79912,HS,Customer Service Rep,Y,LP436002,4308
243388,810029,(803) 766-5875,member73138@gmail.com,Charleston,SC,29414,Some College,Mechanic,Y,973402,NaN
347398,942600,(203) 614-4569,NaN,Hartford,CT,06106,BS,NaN,Y,LP489892,26654
681124,1367726,(260) 861-4993,NaN,Indianapolis,IN,46208,High School,Operator,Yes,INVALID,NaN
348003,943353,(860) 879-6701,stevenjohnson@gmail.com,Cambridge,MA,NaN,College Graduate,Customer Service Rep,No,NaN,NaN
736429,1438122,(412) 899-1943,mmitchell@yahoo.com,Erie,PA,16501,Masters,Homemaker,True,6515-9813,43
366101,966356,(614) 738-0253,olivia.martinez@yahoo.com,Columbus,OH,43229,Graduate Degree,Administrative Assistant,No,NaN,NaN
405516,1016678,(919) 395-8890,mary.roberts@gmail.com,Spartanburg,SC,29615,Some College,Representative,Y,M851409,53
575196,1233207,(773) 536-7727,janetmitchell@gmail.com,Naperville,IL,60540,Bachelors,Teacher,Yes,NaN,NaN
701264,1393462,(248) 555-2921,betty_jones@me.com,Lansing,MI,48910,NaN,Retired,N,NaN,NaN
245746,813058,(214) 565-7763,janet.peterson@spectrum.net,Fort Worth,TX,76102,NaN,Retail Worker,Y,312464,1395

In [13]:
df_product_groups = pd.read_csv('../Data/eci_product_groups.csv')
df_product_groups.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sku               80 non-null     object
 1   product_name      80 non-null     object
 2   price_group_id    80 non-null     object
 3   price_group_name  80 non-null     object
 4   group_type        80 non-null     object
dtypes: object(5)
memory usage: 3.3+ KB

In [14]:
df_product_groups.sample(25)

,sku,product_name,price_group_id,price_group_name,group_type
42,BOOFIMY002,ReadNow Guide Mystery,GIFT_UNDER_50_01,Gift Ideas Under $50,Promotional
66,GROSNCH023,MarketEssentials Premium Chips,MOVIE_NIGHT_01,Movie Night Snacks,Bundle
37,SPOFIAP005,FitZone Performance Apparel,FITNESS_COMBO_01,Complete Fitness Package,Bundle
32,ELEMOAC001,Electra Accessories Ultra X,COMP_SETUP_01,Computer Setup Essentials,Bundle
23,ELEAUHE012,Innovate Headphones Mini X,COMP_SETUP_01,Computer Setup Essentials,Bundle
64,GROSNCH014,TastyBites Organic Chips,MOVIE_NIGHT_01,Movie Night Snacks,Bundle
29,ELECOLA002,Electra Laptops Ultra Pro,COMP_SETUP_01,Computer Setup Essentials,Bundle
35,ELEMOAC009,TechPro Accessories Air X,COMP_SETUP_01,Computer Setup Essentials,Bundle
55,ELECOTA007,Innovate Tablets Mini XL,MOBILE_DEVICES_01,Personal Computing Devices,Substitute
17,CLOWOBO007,ThreadWell Bottoms Collection,CASUAL_BOTTOMS_01,Casual Bottoms,Substitute
41,SPOFISU006,SportsGear Pro Supplements,FITNESS_COMBO_01,Complete Fitness Package,Bundle
1,BOOEDTE002,Bookworm Advanced Textbooks,BACK_TO_SCHOOL_01,Back to School Essentials,Seasonal
34,ELEMOAC008,ByteWare Accessories Air 2025,COMP_SETUP_01,Computer Setup Essentials,Bundle
22,ELEAUHE011,Electra Headphones Pro XL,COMP_SETUP_01,Computer Setup Essentials,Bundle
40,SPOFISU004,FitZone Pro Supplements,FITNESS_COMBO_01,Complete Fitness Package,Bundle
13,CLOMEPA002,DressRight Regular Pants,CASUAL_BOTTOMS_01,Casual Bottoms,Substitute
2,BOOEDTE004,PageTurn Essential Textbooks,BACK_TO_SCHOOL_01,Back to School Essentials,Seasonal
59,GROBESO003,FreshPick Fresh Soda,MOVIE_NIGHT_01,Movie Night Snacks,Bundle
20,ELEAUHE002,TechPro Headphones Air Pro,COMP_SETUP_01,Computer Setup Essentials,Bundle
4,CLOMESH005,StyleX Relaxed Shirts,BACK_TO_SCHOOL_01,Back to School Essentials,Seasonal
7,ELECOLA006,Electra Laptops Edge XL,BACK_TO_SCHOOL_01,Back to School Essentials,Seasonal
73,BOONOSE005,ReadNow Guide Self-Help,WELLNESS_BUNDLE_01,Wellness & Self-Care,Lifestyle
44,BOOFIMY006,Bookworm Essential Mystery,GIFT_UNDER_50_01,Gift Ideas Under $50,Promotional
43,BOOFIMY005,KnowledgeBase Complete Mystery,GIFT_UNDER_50_01,Gift Ideas Under $50,Promotional
58,ELEMOSM006,ByteWare Smartphones Mini S,MOBILE_DEVICES_01,Personal Computing Devices,Substitute

In [3]:
df_product_master = pd.read_csv('../Data/eci_product_master.csv')
df_product_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   sku                   861 non-null    object
 1   product_name          861 non-null    object
 2   category              861 non-null    object
 3   group                 861 non-null    object
 4   subgroup              861 non-null    object
 5   brand                 861 non-null    object
 6   base_price            861 non-null    float64
 7   initial_ticket_price  861 non-null    float64
 8   costos                861 non-null    float64
dtypes: float64(3), object(6)
memory usage: 60.7+ KB

In [4]:
df_product_master.sample(25)

,sku,product_name,category,group,subgroup,brand,base_price,initial_ticket_price,costos
363,SPOFIAP006,SportsGear Endurance Apparel,Sports,Fitness,Apparel,SportsGear,80.33,98.80,51.53
383,SPOTESO003,ActiveLife Pro Soccer,Sports,Team Sports,Soccer,ActiveLife,103.21,130.81,62.57
769,GROPABA006,PantryBasics Organic Baking,Groceries,Pantry,Baking,PantryBasics,10.46,12.23,7.50
39,ELEMOSM011,TechPro Smartphones Smart S,Electronics,Mobile,Smartphones,TechPro,262.38,316.92,205.68
698,GROBEJU002,GoodEats Premium Juice,Groceries,Beverages,Juice,GoodEats,9.14,11.11,7.48
354,SPOFIEQ007,FitZone Active Equipment,Sports,Fitness,Equipment,FitZone,99.65,118.01,56.07
291,HOMCOPO004,HomeMaker Professional Pots & Pans XL,Home & Kitchen,Cookware,Pots & Pans,HomeMaker,77.07,87.18,38.93
407,SPOOUCA004,OutdoorEdge Active Camping,Sports,Outdoor,Camping,OutdoorEdge,77.43,99.79,43.74
344,HOMFUDI006,HomeStyle Premium Dining Set,Home & Kitchen,Furniture,Dining,HomeStyle,71.35,79.58,37.40
213,CLOWOOU019,StyleX Relaxed Outerwear,Clothing,Women,Outerwear,StyleX,47.54,55.35,21.53
81,ELEAUSP006,Electra Speakers Ultra S,Electronics,Audio,Speakers,Electra,284.41,365.66,185.53
432,BOOFIRO001,ReadNow Guide Romance,Books,Fiction,Romance,ReadNow,21.67,26.59,9.01
575,BEAHATR006,RadiantSkin Perfect Treatment,Beauty,Haircare,Treatment,RadiantSkin,32.99,42.86,13.26
431,BOOFIMY010,ReadNow Complete Mystery,Books,Fiction,Mystery,ReadNow,26.88,30.65,13.98
765,GROPABA002,PantryBasics Natural Baking,Groceries,Pantry,Baking,PantryBasics,8.02,8.88,5.88
254,CLOCHIN013,StyleX Regular Infants,Clothing,Children,Infants,StyleX,44.96,49.76,25.25
780,GROPABA017,PantryBasics Fresh Baking,Groceries,Pantry,Baking,PantryBasics,10.99,12.27,7.81
167,CLOWOTO006,DressRight Tops Collection,Clothing,Women,Tops,DressRight,50.71,64.04,25.17
613,BEAMALI012,GlowUp Essential Lips,Beauty,Makeup,Lips,GlowUp,35.58,42.22,13.32
88,ELEAUHO002,CircuitCity Home Audio Edge X,Electronics,Audio,Home Audio,CircuitCity,345.27,427.93,262.79
46,ELEMOWE006,CircuitCity Wearables Ultra Pro,Electronics,Mobile,Wearables,CircuitCity,283.63,366.58,225.70
70,ELEAUHE009,Electra Headphones Air XL,Electronics,Audio,Headphones,Electra,305.84,376.30,230.54
423,BOOFIMY002,ReadNow Guide Mystery,Books,Fiction,Mystery,ReadNow,22.91,29.14,11.55
131,CLOMEJA010,ThreadWell Jackets Collection,Clothing,Men,Jackets,ThreadWell,55.52,71.40,27.82
208,CLOWOOU014,Attire Athletic Outerwear,Clothing,Women,Outerwear,Attire,52.35,62.43,26.46

In [20]:
df_stores_clusters = pd.read_csv('../Data/eci_stores_clusters.csv')
df_stores_clusters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STORE_ID    157 non-null    object
 1   BRAND       157 non-null    object
 2   STORE_NAME  157 non-null    object
 3   CLUSTER     140 non-null    object
dtypes: object(4)
memory usage: 5.0+ KB

In [21]:
df_stores_clusters.sample(25)

,STORE_ID,BRAND,STORE_NAME,CLUSTER
102,S00103,EssentialsPlus,EssentialsPlus - Columbus,GA_Cluster
20,S00021,AsterionHouse,AsterionHouse - Mesa,Mountain_Cluster
63,S00064,LuxeRetail,LuxeRetail - Houston,Texas_Cluster
101,S00102,MarketExpress,MarketExpress - Elizabeth,NJ_Cluster
153,S00154,BudgetShop,BudgetShop - Newark,NJ_Cluster
76,S00077,MegaShop,MegaShop - Erie,PA_Cluster
67,S00068,MarketExpress,MarketExpress - Lakewood,Mountain_Cluster
18,S00019,QuickBuy,QuickBuy - Rochester,NY_Cluster
116,S00117,QuickBuy,QuickBuy Greensboro Westside,NC_Cluster
3,STORE0004,MegaShop,MegaShop - Oklahoma City,Texas_Cluster
109,S00110,EssentialsPlus,EssentialsPlus Detroit Downtown,Ohio_Great_Lakes
100,S00101,BudgetShop,BudgetShop - Albany,NY_Cluster
72,000073,AsterionHouse,AsterionHouse - Atlanta,GA_Cluster
30,S00031,EssentialsPlus,EssentialsPlus - Tulsa,NaN
52,000053,MegaShop,MegaShop Carmel Eastside,Midwest_Cluster
25,S00026,AsterionHouse,AsterionHouse - South Bend,Midwest_Cluster
66,S00067,LuxeRetail,LuxeRetail Glendale Uptown,Mountain_Cluster
120,S00121,EssentialsPlus,EssentialsPlus - Spokane,Cluster_West_Coast
65,S00066,MarketExpress,MarketExpress - New York,NY_Cluster
79,S00080,AsterionHouse,AsterionHouse - Augusta,GA_Cluster
88,S00089,QuickBuy,QuickBuy - Houston,Texas_Cluster
47,S00048,PrimeGoods,PrimeGoods - Allentown,PA_Cluster
49,STORE0050,EssentialsPlus,EssentialsPlus - New York,NY_Cluster
115,STORE0116,MarketExpress,MarketExpress Hillsboro Eastside,Cluster_West_Coast
11,S00012,PrimeGoods,PrimeGoods - Savannah,GA_Cluster

In [23]:
df_stores = pd.read_csv('../Data/eci_stores.csv')
df_stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STORE_ID    157 non-null    object
 1   BRAND       157 non-null    object
 2   STORE_NAME  157 non-null    object
 3   ADDRESS1    157 non-null    object
 4   ADDRESS2    43 non-null     object
 5   CITY        157 non-null    object
 6   STATE       157 non-null    object
 7   ZIP         151 non-null    object
 8   OPENDATE    157 non-null    object
 9   CLOSEDATE   18 non-null     object
 10  STORE_TYPE  155 non-null    object
 11  REGION      157 non-null    object
dtypes: object(12)
memory usage: 14.8+ KB

In [25]:
df_stores.head(25)

,STORE_ID,BRAND,STORE_NAME,ADDRESS1,ADDRESS2,CITY,STATE,ZIP,OPENDATE,CLOSEDATE,STORE_TYPE,REGION
0,S00001,PrimeGoods,PrimeGoods - Hillsboro,5735 NE Washington Pl,NaN,Hillsboro,OR,74820,2015-01-10 00:00:00,NaN,Express,West
1,S00002,MegaShop,MegaShop Indianapolis Eastside,3557 Cedar Ct,Unit 89,Indianapolis,IN,33483-1775,2012-03-23 00:00:00,NaN,Express,Midwest
2,STORE0003,MarketExpress,MarketExpress - Las Vegas,7870 W Church Ave,NaN,Las Vegas,NV,49099,2021-09-23 00:00:00,NaN,Outlet,West
3,STORE0004,MegaShop,MegaShop - Oklahoma City,3105 N Washington Pl,NaN,Oklahoma City,OK,80592,06/30/2015,NaN,Mall,Southwest
4,S00005,PrimeGoods,PrimeGoods - Charlotte,8756 SW Maple Ln,Suite 848,Charlotte,NC,32299,2019-06-10 00:00:00,NaN,Express,Southeast
5,000006,AsterionHouse,AsterionHouse - Miami,1307 NE Maple Ct,NaN,Miami,FL,13748,2014-02-24 00:00:00,2028-02-21 00:00:00,Mall,Southeast
6,S00007,LuxeRetail,LuxeRetail - Miami,699 Oak Dr,Building A,Miami,FL,36309,2020-10-10 00:00:00,NaN,Mall,Southeast
7,000008,LuxeRetail,LuxeRetail Macon Downtown,9987 SW River Rd,Floor 4,Macon,GA,93879,2014-04-30 00:00:00,NaN,Express,Southeast
8,S00009,MegaShop,MegaShop Detroit Center,5424 Cedar Ln,NaN,Detroit,MI,52642,2016-10-17 00:00:00,2029-10-14 00:00:00,Flagship,Midwest
9,S00010,AsterionHouse,AsterionHouse - Warren,957 E Main Rd,Floor 4,Warren,MI,96416,2007-02-23 00:00:00,NaN,Outlet,Midwest
10,S00011,FamilyStore,FamilyStore Indianapolis Eastside,7997 NW Maple Blvd,NaN,Indianapolis,IN,NaN,2014-01-13 00:00:00,NaN,Mall,Midwest
11,S00012,PrimeGoods,PrimeGoods - Savannah,5443 SW Park Ave,NaN,Savannah,GA,92074,2019-05-07 00:00:00,NaN,Street,Southeast
12,S00013,MarketExpress,MarketExpress - El Paso,4496 N Pine Way,Building B,El Paso,TX,NaN,2019-10-14 00:00:00,NaN,Mall,Southwest
13,S00014,FamilyStore,FamilyStore - Erie,4143 Park Rd,Suite 469,Erie,PA,35945,2014-11-05 00:00:00,NaN,Street,Northeast
14,S00015,MegaShop,MegaShop - Houston,3344 SE Church Ln,NaN,Houston,TX,77215,2017-06-11 00:00:00,NaN,Street,Southwest
15,S00016,EssentialsPlus,EssentialsPlus Peoria Uptown,2850 E Hill Blvd,NaN,Peoria,IL,14611,2014-12-31 00:00:00,NaN,Express,Midwest
16,000017,PrimeGoods,PrimeGoods - Chicago,3914 E Green Ave,Suite 853,Chicago,IL,25305,2008-02-10 00:00:00,NaN,Mall,Midwest
17,S00018,AsterionHouse,AsterionHouse - San Diego,4080 S Main Way,NaN,San Diego,CA,54811,2020-09-26 00:00:00,NaN,Superstore,West
18,S00019,QuickBuy,QuickBuy - Rochester,4172 W View Rd,NaN,Rochester,NY,99112,2014-08-17 00:00:00,NaN,Mall,Northeast
19,S00020,FamilyStore,FamilyStore - Cleveland,4847 S Hill St,Unit 46,Cleveland,OH,93460,2013-05-29 00:00:00,NaN,Street,Midwest
20,S00021,AsterionHouse,AsterionHouse - Mesa,8906 Washington Blvd,Floor 4,Mesa,AZ,52918,2014-10-31 00:00:00,2023-10-29,Boutique,Southwest
21,STORE0022,EssentialsPlus,EssentialsPlus - Spartanburg,6191 Forest St,NaN,Spartanburg,SC,34504,2015-11-19 00:00:00,NaN,Mall,Southeast
22,STORE0023,MarketExpress,MarketExpress - Los Angeles,6133 View Blvd,NaN,Los Angeles,CA,60990,2010-06-13 00:00:00,NaN,Express,West
23,S00024,FamilyStore,FamilyStore - Rochester,8703 E Church Way,NaN,Rochester,NY,90642,2014-07-07 00:00:00,NaN,Mall,Northeast
24,S00025,MarketExpress,MarketExpress - Fort Wayne,250 SE Elm Blvd,NaN,Fort Wayne,IN,34285,2020-06-07 00:00:00,NaN,Boutique,Midwest

## Transacciones

In [11]:
df_transactions = pd.read_csv('../Data/eci_transactions.csv')
df_transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19004759 entries, 0 to 19004758
Data columns (total 9 columns):
 #   Column                  Dtype
---  ------                  -----
 0   TRANSACTION_ID          int64
 1   DATE                    object
 2   STORE_ID                object
 3   SKU                     object
 4   QUANTITY                float64
 5   PRICE                   float64
 6   TOTAL_SALES             float64
 7   SUBGROUP                object
 8   STORE_SUBGROUP_DATE_ID  object
dtypes: float64(3), int64(1), object(5)
memory usage: 1.3+ GB

In [12]:
df_transactions.sample(25)

,TRANSACTION_ID,DATE,STORE_ID,SKU,QUANTITY,PRICE,TOTAL_SALES,SUBGROUP,STORE_SUBGROUP_DATE_ID
365014,370391,2021-01-21,000079,BOOEDTE010,1.0,23.29,23.29,Textbooks,000079_Textbooks_2021-01-21
13050710,13049518,2022-12-28,S00108,BEAMAFA010,NaN,48.86,48.86,Face,S00108_Face_2022-12-28
5207070,5204116,2021-10-16,000052,HOMFULI003,1.0,56.89,56.89,Living Room,000052_Living Room_2021-10-16
11496738,11497123,2022-10-08,S00062,SPOOUCA001,1.0,73.66,73.66,Camping,S00062_Camping_2022-10-08
4703464,4712850,2021-09-21,S00155,ELEMOSM008,1.0,269.41,269.41,Smartphones,S00155_Smartphones_2021-09-21
18024604,18034244,2023-11-06,S00128,BEAHATR005,1.0,38.44,38.44,Treatment,S00128_Treatment_2023-11-06
17565406,17570194,2023-10-11,S00085,HOMAPMA009,1.0,86.76,86.76,Major Appliances,S00085_Major Appliances_2023-10-11
4245,1145,2021-01-01,S00009,GROPABA018,3.0,9.61,28.82,Baking,S00009_Baking_2021-01-01
4831207,4815120,2021-09-27,000006,TOYEDLE003,1.0,27.54,27.54,Learning,000006_Learning_2021-09-27
4649863,4644787,2021-09-18,000094,CLOWODR011,1.0,46.54,46.54,Dresses,000094_Dresses_2021-09-18
1392111,1384854,2021-03-22,S00011,HOMFULI001,3.0,66.98,200.93,Living Room,S00011_Living Room_2021-03-22
4907317,4912410,2021-10-01,S00137,SPOFIAP001,2.0,94.98,189.96,Apparel,S00137_Apparel_2021-10-01
11862145,11857639,2022-10-27,000006,GROSNCH021,1.0,10.49,10.49,Chips,000006_Chips_2022-10-27
2023048,2020685,2021-04-30,S00074,BEASKCL006,1.0,43.46,43.46,Cleansers,S00074_Cleansers_2021-04-30
18783569,18780706,2023-12-18,S00007,HOMAPSM001,1.0,87.71,87.71,Small Appliances,S00007_Small Appliances_2023-12-18
5714462,5703426,2021-11-10,S00060,BOONOSE007,2.0,18.32,36.65,Self-Help,S00060_Self-Help_2021-11-10
3282674,3274834,2021-07-11,S00066,SPOOUCA002,2.0,83.26,166.53,Camping,S00066_Camping_2021-07-11
2624355,2620902,2021-06-05,S00066,BEAHAST004,1.0,45.59,45.59,Styling,S00066_Styling_2021-06-05
15163934,15156195,2023-05-19,STORE0003,ELEAUHO003,1.0,326.28,326.28,Home Audio,STORE0003_Home Audio_2023-05-19
6431123,6425319,2021-12-15,S00103,GROPAPA012,1.0,11.04,11.04,Pasta,S00103_Pasta_2021-12-15
12331001,12329494,2022-11-20,S00127,TOYACPL006,3.0,26.44,79.32,Playsets,S00127_Playsets_2022-11-20
5838133,5846807,2021-11-17,S00104,HOMFUDI007,1.0,80.54,80.54,Dining,S00104_Dining_2021-11-17
2675565,2680133,2021-06-08,STORE0149,BOONOSE001,2.0,25.82,51.65,Self-Help,STORE0149_Self-Help_2021-06-08
18802735,18801180,2023-12-19,S00045,TOYGABO003,1.0,23.80,23.80,Board Games,S00045_Board Games_2023-12-19
4383761,4373910,2021-09-04,S00074,GROBEJU008,1.0,8.20,8.20,Juice,S00074_Juice_2021-09-04

In [13]:
duplicados = df_transactions['TRANSACTION_ID'].duplicated()
df_transactions[duplicados]

Empty DataFrame
Columns: [TRANSACTION_ID, DATE, STORE_ID, SKU, QUANTITY, PRICE, TOTAL_SALES, SUBGROUP, STORE_SUBGROUP_DATE_ID]
Index: []

No se observan id duplicados en transactions.

### Análisis

Para conocer las ganancias añadiremos los valores de base_price, initial_ticket_price y costos. Según los datos de product_master

In [15]:
df_transactions= pd.merge(df_transactions, df_product_master, left_on='SKU', right_on='sku', how='left')
df_transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19159425 entries, 0 to 19159424
Data columns (total 18 columns):
 #   Column                  Dtype
---  ------                  -----
 0   TRANSACTION_ID          int64
 1   DATE                    object
 2   STORE_ID                object
 3   SKU                     object
 4   QUANTITY                float64
 5   PRICE                   float64
 6   TOTAL_SALES             float64
 7   SUBGROUP                object
 8   STORE_SUBGROUP_DATE_ID  object
 9   sku                     object
 10  product_name            object
 11  category                object
 12  group                   object
 13  subgroup                object
 14  brand                   object
 15  base_price              float64
 16  initial_ticket_price    float64
 17  costos                  float64
dtypes: float64(6), int64(1), object(11)
memory usage: 2.6+ GB

In [16]:
df_transactions.sample(25)

,TRANSACTION_ID,DATE,STORE_ID,SKU,QUANTITY,PRICE,TOTAL_SALES,SUBGROUP,STORE_SUBGROUP_DATE_ID,sku,product_name,category,group,subgroup,brand,base_price,initial_ticket_price,costos
16465443,16320419,2023-08-01,S00038,BEAMALI002,1.0,31.73,31.73,Lips,S00038_Lips_2023-08-01,BEAMALI002,RadiantSkin Pure Lips,Beauty,Makeup,Lips,RadiantSkin,33.57,42.05,14.50
2410743,2388643,2021-05-22,S00088,SPOFISU001,1.0,100.75,100.75,Supplements,S00088_Supplements_2021-05-22,SPOFISU001,SportsGear Sport Supplements,Sports,Fitness,Supplements,SportsGear,100.05,111.22,55.28
17908571,17758132,2023-10-22,S00013,GROSNCH008,2.0,9.68,19.36,Chips,S00013_Chips_2023-10-22,GROSNCH008,TastyBites Organic Chips,Groceries,Snacks,Chips,TastyBites,10.17,13.09,8.62
18776244,18617344,2023-12-08,S00013,TOYACFI002,3.0,31.34,94.01,Figures,S00013_Figures_2023-12-08,TOYACFI002,PlayFun Smart Figures,Toys,Action,Figures,PlayFun,31.22,40.49,17.65
14609010,14488129,2023-04-02,S00019,BOONOHI009,1.0,21.88,21.88,History,S00019_History_2023-04-02,BOONOHI009,PageTurn Advanced History,Books,Non-Fiction,History,PageTurn,26.82,32.82,12.73
3155,15454,2021-01-01,STORE0133,TOYACVE004,3.0,30.34,91.01,Vehicles,STORE0133_Vehicles_2021-01-01,TOYACVE004,KidJoy Adventure Vehicles,Toys,Action,Vehicles,KidJoy,30.82,35.15,16.15
10477208,10386861,2022-08-10,S00065,SPOTEBA001,1.0,80.41,80.41,Baseball,S00065_Baseball_2022-08-10,SPOTEBA001,SportsGear Endurance Basketball,Sports,Team Sports,Basketball,SportsGear,103.03,126.83,64.02
12559996,12460165,2022-11-27,S00040,BOOEDRE002,1.0,24.19,24.19,Reference,S00040_Reference_2022-11-27,BOOEDRE002,KnowledgeBase Guide Reference,Books,Educational,Reference,KnowledgeBase,25.18,27.83,11.88
17040287,16905058,2023-09-03,S00085,SPOOUCA002,3.0,77.17,231.52,Camping,S00085_Camping_2023-09-03,SPOOUCA002,SportsGear Active Camping,Sports,Outdoor,Camping,SportsGear,79.94,98.81,40.96
16920301,16788280,2023-08-27,STORE0149,ELEAUHO003,1.0,280.80,280.80,Home Audio,STORE0149_Home Audio_2023-08-27,ELEAUHO003,Electra Home Audio Ultra 2025,Electronics,Audio,Home Audio,Electra,324.29,375.76,228.27
6459048,6404259,2021-12-14,S00080,CLOCHIN009,1.0,42.11,42.11,Infants,S00080_Infants_2021-12-14,CLOCHIN009,ThreadWell Infants Collection,Clothing,Children,Infants,ThreadWell,42.33,51.88,25.02
6556460,6500563,2021-12-19,S00117,TOYACFI009,3.0,36.62,109.86,Figures,S00117_Figures_2021-12-19,TOYACFI009,PlayTime Smart Figures,Toys,Action,Figures,PlayTime,35.59,41.62,18.20
579357,571447,2021-02-01,S00128,HOMFUDI006,1.0,76.20,76.20,Dining,S00128_Dining_2021-02-01,HOMFUDI006,HomeStyle Premium Dining Set,Home & Kitchen,Furniture,Dining,HomeStyle,71.35,79.58,37.40
626939,619724,2021-02-04,S00088,HOMCOBA002,1.0,99.27,99.27,Bakeware,S00088_Bakeware_2021-02-04,HOMCOBA002,CookEasy Premium Bakeware,Home & Kitchen,Cookware,Bakeware,CookEasy,92.67,103.52,46.58
9638373,9564072,2022-06-25,S00039,GROSNCO018,1.0,9.80,9.80,Cookies,S00039_Cookies_2022-06-25,GROSNCO018,PantryBasics Natural Cookies,Groceries,Snacks,Cookies,PantryBasics,9.33,10.31,6.57
15464439,15331061,2023-05-31,S00014,BEASKTR003,2.0,44.70,89.39,Treatments,S00014_Treatments_2023-05-31,BEASKTR003,BeautyBasics Pure Treatments,Beauty,Skincare,Treatments,BeautyBasics,42.58,53.06,17.52
18185608,18047098,2023-11-07,S00080,TOYEDAR004,1.0,28.23,28.23,Arts & Crafts,S00080_Arts & Crafts_2023-11-07,TOYEDAR004,ImagineThat Adventure Arts & Crafts,Toys,Educational,Arts & Crafts,ImagineThat,28.37,36.81,12.58
12054840,11954045,2022-11-01,S00013,CLOCHIN011,3.0,56.81,170.43,Infants,S00013_Infants_2022-11-01,CLOCHIN011,ThreadWell Slim Infants,Clothing,Children,Infants,ThreadWell,52.39,67.00,27.77
15469907,15349673,2023-06-01,S00081,GROSNNU010,1.0,8.98,8.98,Nuts,S00081_Nuts_2023-06-01,GROSNNU010,TastyBites Premium Nuts,Groceries,Snacks,Nuts,TastyBites,8.55,10.11,6.67
12232434,12142211,2022-11-10,S00152,CLOCHIN011,2.0,47.46,94.92,Infants,S00152_Infants_2022-11-10,CLOCHIN011,ThreadWell Slim Infants,Clothing,Children,Infants,ThreadWell,52.39,67.00,27.77
5431229,5383312,2021-10-25,S00047,GROSNCO007,2.0,10.64,21.28,Cookies,S00047_Cookies_2021-10-25,GROSNCO007,GoodEats Fresh Cookies,Groceries,Snacks,Cookies,GoodEats,11.21,14.18,8.30
2216540,2198615,2021-05-11,S00047,ELEMOWE001,2.0,231.15,462.31,Wearables,S00047_Wearables_2021-05-11,ELEMOWE001,CircuitCity Wearables Elite 2025,Electronics,Mobile,Wearables,CircuitCity,253.20,300.15,173.24
16054612,15918264,2023-07-08,S00065,TOYACVE002,2.0,36.18,72.36,Vehicles,S00065_Vehicles_2023-07-08,TOYACVE002,KidJoy Creative Vehicles,Toys,Action,Vehicles,KidJoy,31.50,37.19,15.68
17262686,17119291,2023-09-16,S00058,CLOWOBO011,1.0,50.05,50.05,Bottoms,S00058_Bottoms_2023-09-16,CLOWOBO011,StyleX Bottoms Collection,Clothing,Women,Bottoms,StyleX,50.27,59.28,28.53
12937930,12835864,2022-12-16,S00069,BEASKMO001,1.0,34.86,34.86,Moisturizers,S00069_Moisturizers_2022-12-16,BEASKMO001,PrettyYou Luxe Moisturizers,Beauty,Skincare,Moisturizers,PrettyYou,38.46,47.83,14.83

In [29]:
df_test = pd.read_csv('../Data/ids_test.csv')
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77700 entries, 0 to 77699
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   STORE_SUBGROUP_DATE_ID  77700 non-null  object
dtypes: object(1)
memory usage: 607.2+ KB

In [30]:
df_test.sample(25)

                   STORE_SUBGROUP_DATE_ID
44461            S00089_Coffee_2024-01-05
47499           S00095_Styling_2024-01-05
25830            000053_Baking_2024-01-01
59948              S00122_Eyes_2024-01-01
70191      S00143_Water Sports_2024-01-03
27603  S00057_Major Appliances_2024-01-03
64154             S00131_Pasta_2024-01-07
20867  S00043_Major Appliances_2024-01-01
64200          S00131_Vehicles_2024-01-04
41838             S00084_Chips_2024-01-07
48968           S00099_Romance_2024-01-04
72806   S00148_Science Fiction_2024-01-07
19200         S00040_Wearables_2024-01-07
26481            S00055_Shirts_2024-01-01
45878      STORE0092_Self-Help_2024-01-01
39730           S00080_Styling_2024-01-06
15227         S00032_Equipment_2024-01-03
39323     000079_Arts & Crafts_2024-01-05
58147          STORE0118_Girls_2024-01-06
21217       S00043_Board Games_2024-01-01
51917         S00106_Outerwear_2024-01-06
28548        S00059_Home Audio_2024-01-03
14394              S00030_Nuts_2024-01-03
21314             S00044_Pants_2024-01-07
17980         S00037_Treatment_2024-01-05